theme: jekyll-theme-hacker
inicio de la primera prectica e induccion a la plataforma 
des arrollo del SAP en esta plataforma para realizar un seguimiento 
segun los lineamientos y requesitos que exigen en el contrato y ASI
